### ISSUE TITLE
Cannot release

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1150]
```
1) System.Exception: Could not run "git clone -b gh-pages --single-branch git@github.com:fsprojects/VisualFSharpPowerTools.git temp/gh-pages".
Error:
Cloning into 'temp/gh-pages'...
Warning: Permanently added 'github.com,192.30.252.129' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
   at Fake.Git.CommandHelper.runSimpleGitCommand@89-2.Invoke(String message) in C:\code\fake\src\app\FakeLib\Git\CommandHelper.fs:line 89
   at Fake.Git.CommandHelper.runSimpleGitCommand(String repositoryDir, String command) in C:\code\fake\src\app\FakeLib\Git\CommandHelper.fs:line 89
   at Fake.Git.Repository.cloneSingleBranch(String workingDir, String repoUrl, String branchName, String toPath) in C:\code\fake\src\app\FakeLib\Git\Repository.fs:line 25
   at FSI_0001.Build.clo@187-17.Invoke(Unit _arg6) in D:\git\VisualFSharpPowerTools\build.fsx:line 190
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 411
```

**Comment by vasily-kirichenko** [comment]
@forki any ideas?

**Comment by forki** [comment]
No sorry.

**Comment by vasily-kirichenko** [comment]
@forki could you try to release?

**Comment by dungpa** [comment]
Try 'git blame' on Release target in build.fsx. Revert the related commit I made some time ago.

**Comment by vasily-kirichenko** [comment]
@dungpa Reverted the commit
@forki switched to https for git push
============> success until it tried to release on github:
```
Created draft release id 1942429
Running build failed.
Error:
System.OperationCanceledException: The operation was canceled.
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 411
```

**Comment by vasily-kirichenko** [comment]
Uploaded the VSIX by hand to github and to VS Gallery. The remaining problem is that VS does not show that there is an update :( Any ideas?

**Comment by dungpa** [comment]
VS gallery shows correct version. It may take a while. You can search the extension in VS to verify new the version.

**Comment by vasily-kirichenko** [comment]
ah, I've installed the new version, that's why no notification :)

**Comment by forki** [comment]
Where is the announcement tweet for me to retweet? ;-)

**Comment by vasily-kirichenko** [comment]
Done :)
