### ISSUE TITLE
Integration with FSharpLint doesn't work

### ISSUE THREAD

**Issue by sideeffffect** [fsprojects/VisualFSharpPowerTools#1153]
In VS Options *F# Power Tools* -> *Lint* gives *An error occurred loading this property page*.

**Comment by vasily-kirichenko** [comment]
@duckmatt could you look at it ASAP?

**Comment by vasily-kirichenko** [comment]
I cannot reproduce it, unfortunately.

**Comment by duckmatt** [comment]
I can't seem to recreate this either, couple of questions to help diagnose:
* What version of Visual Studio are you using?* Does this error occur for all projects or a specific project?* Have you tried re-installing the extension?* Is there any related information in the [Activity Log](http://blogs.msdn.com/b/visualstudio/archive/2010/02/24/troubleshooting-with-the-activity-log.aspx
I'll try to take a look during my lunch break and after work

Date: Mon, 12 Oct 2015 02:23:45 -0700

**Comment by sideeffffect** [comment]
* What version of Visual Studio are you using?
  * VS 2013
* Does this error occur for all projects or a specific project?
  * all projects I tried
* Have you tried re-installing the extension?
  * not yet, just updated to the latest version; I will try that now
* Is there any related information in the [Activity Log](http://blogs.msdn.com/b/visualstudio/archive/2010/02/24/troubleshooting-with-the-activity-log.aspx)
  * I'm not sure: http://pasted.co/dd0b5288

**Comment by vasily-kirichenko** [comment]
@sideeffffect could you be so patient to clone VFPT repository, build it and run an experimental VS instance under the debugger (set active project to `FSharpVSPowerTools` (the only C# one in the solution)) and watch for exceptions?

**Comment by sideeffffect** [comment]
> experimental VS instance

what is that? I'm asking because I can't install any software, I can only use the normal VS 2013 that I have.

**Comment by vasily-kirichenko** [comment]
It will be launched when you press F5. It's a normal VS, but with clean settings. Also you need VS SDK installed (it's a small VS component).

**Comment by TeaDrivenDev** [comment]
I'm seeing this too, with VS 2013 and 2015, even with no project/solution open at all. I uninstalled and reinstalled in 2015, with no change.

I can add that the first time accessing options dialog per Visual Studio session, it produces the message stated by @sideeffffect; after that, the "Lint" properties page is completely empty until you restart Visual Studio.

Also, the actual FSharpLint integration appears to work; I'm getting markers for too many class members or too long lambda functions. It's just the settings that aren't accessible.

I have now run it in a VS 2013 experimental instance, and "unfortunately", it's working there. With no project open, I get the correct message about at least one project needing to be open, and when I open one, I can access the "Lint" settings page. Changing settings does not change the linting messages that should change, however.

**Comment by dungpa** [comment]
@TeaDrivenDev Could you try to clear Visual Studio Component Model Cache http://stackoverflow.com/a/17604007 ? Maybe it's something funky with the cache.

**Comment by TeaDrivenDev** [comment]
@dungpa I tried that in both Visual Studio versions; no change there.

**Comment by dungpa** [comment]
@TeaDrivenDev I don't understand what is difference between using the extension in normal hives and Exp hives here. Could you try with `devenv /updateconfiguration` as described at http://stackoverflow.com/questions/22300278/registering-an-unpacked-vsix-extension-via-msi-without-using-devenv-setup ? Sorry for the troubles.

**Comment by TeaDrivenDev** [comment]
I don't think there is a difference between experimental and normal hives per se. I ran VS 2015 with a new RootSuffix and installed only VFPT, and that worked. So the issue is likely something that has "happened" to the other profiles.

I tried running `devenv /updateconfiguration` and then `devenv /clearcache`, as explained [here](https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/mef.md) (linked from that SO question), but again no change.

**Comment by duckmatt** [comment]
Thanks for the information @TeaDrivenDev would you be able to post a list of your extensions? Hopefully with those installed I may be able to recreate the error

@dungpa Is [this](https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools.Logic/Linting/LintUtils.fs#L14) an expected way to retrieve a list of project paths? I'm thinking isn't related to another extension, it could be to do with the use of `EnvDTE` here

**Comment by TeaDrivenDev** [comment]
@duckmatt I don't think it's related to getting the project paths, because the behavior is already wrong when there is no project open at all (error message vs. "no project open" message).

My installed extensions in VS 2015 (slightly different in 2013) are the following:

Better Start Page
CodeLineage
CodeMaid
File Nesting
Git Diff Margin
Git Tools
MultiEditing
NCrunch
OzCode
Paket
Productivity Power Tools
ReSharper
Smooth Caret
SwitchStartupProject
TabSanity
Web Essentials

I have now installed all except ReSharper in my above mentioned new test hive, and it still works there.

**Comment by dungpa** [comment]
@TeaDrivenDev @sideeffffect I produced a new build v2.1.1 that includes some more logging https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.2.0-a1510132010/artifacts. 

If you install this version and enable Diagnostics mode http://fsprojects.github.io/VisualFSharpPowerTools/faq.html#What-is-Diagnostic-mode-When-should-I-use-it, there might be some logs for us to find out the root cause. Thanks.

**Comment by TeaDrivenDev** [comment]
That outputs this when switching to the "Lint" properties page for the first time in VS 2015 (nothing at all in 2013, though):

```
[VFPT][Error 10:47:04 ] Exception Message: 'Cannot set unknown member 'System.Windows.Interactivity.InvokeCommandAction.Command'.' Line number '84' and line position '45'.
Stack Trace:    at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, Boolean skipJournaledProperties, Uri baseUri)
   at System.Windows.Markup.XamlReader.Load(XamlReader xamlReader, ParserContext parserContext)
   at System.Windows.Markup.XamlReader.Load(XmlReader reader, ParserContext parserContext, XamlParseMode parseMode)
   at System.Windows.Markup.XamlReader.Load(Stream stream, ParserContext parserContext)
   at System.Windows.Markup.XamlReader.Load(Stream stream)
   at FsXaml.LoadXaml.from[a](String file, Type t)
   at FsXaml.FactoryUtilities.loadChildIfNull[a,b](a root, String resourceFile, b self)
   at FsXaml.XamlContainer..ctor(FrameworkElement content, String resourceFile)
   at FSharpVSPowerTools.Linting.LintOptionsControlProvider..ctor()
   at <StartupCode$FSharpVSPowerTools-Logic>.$LintOptionsPage.-ctor@26-182.Invoke(Unit unitVar)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at <StartupCode$FSharpVSPowerTools-Logic>.$LintOptionsPage.get_Child@122.Invoke(Unit _arg3)
   at FSharpVSPowerTools.ProjectSystem.VSUtils.protectOrDefault[a](FSharpFunc`2 f, a defaultVal)
[VFPT][Error 10:47:04 ] Exception Message: 'Cannot set unknown member 'System.Windows.Interactivity.InvokeCommandAction.Command'.' Line number '84' and line position '45'.
Stack Trace:    at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, Boolean skipJournaledProperties, Uri baseUri)
   at System.Windows.Markup.XamlReader.Load(XamlReader xamlReader, ParserContext parserContext)
   at System.Windows.Markup.XamlReader.Load(XmlReader reader, ParserContext parserContext, XamlParseMode parseMode)
   at System.Windows.Markup.XamlReader.Load(Stream stream, ParserContext parserContext)
   at System.Windows.Markup.XamlReader.Load(Stream stream)
   at FsXaml.LoadXaml.from[a](String file, Type t)
   at FsXaml.FactoryUtilities.loadChildIfNull[a,b](a root, String resourceFile, b self)
   at FsXaml.XamlContainer..ctor(FrameworkElement content, String resourceFile)
   at FSharpVSPowerTools.Linting.LintOptionsControlProvider..ctor()
   at <StartupCode$FSharpVSPowerTools-Logic>.$LintOptionsPage.-ctor@26-182.Invoke(Unit unitVar)
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at <StartupCode$FSharpVSPowerTools-Logic>.$LintOptionsPage.OnActivate@86.Invoke(Unit _arg2)
   at FSharpVSPowerTools.ProjectSystem.VSUtils.protectOrDefault[a](FSharpFunc`2 f, a defaultVal)
```

Every activation of "Lint" after that first time only logs the second stack trace again.

**Comment by dungpa** [comment]
@ReedCopsey Would you mind having a quick look? I guess this is a totally new use case for FsXaml where its XAML control is used as a Visual Studio options dialog by inheriting `UIElementDialogPage`.

It's really mysterious since the error occurs for some users but not for others. Please see the stack trace above and the code at https://github.com/fsprojects/VisualFSharpPowerTools/tree/master/src/FSharpVSPowerTools.Logic/Linting . 

Your help would be really appreciated.

**Comment by ReedCopsey** [comment]
@dungpa I'll take a look and see if I can figure out what's happening.

**Comment by ReedCopsey** [comment]
@dungpa @TeaDrivenDev Given your stack trace, the problem is that it's failing trying to load and setup System.Windows.Interactivity's InvokeCommandAction here: https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools.Logic/LintOptionsPageControl.xaml#L83-L85

Is there a way to diagnose which version of System.Windows.Interactivity.dll is being loaded in Visual Studio when this fails?  My suspicion is that you're getting the wrong version loaded somehow, potentially from another extension. (It works here, in VS 2013, with no issues...)

**Comment by TeaDrivenDev** [comment]
@ReedCopsey Hmmm.... fuslogvw.exe, maybe? Worth a try at least, I guess.

**Comment by TeaDrivenDev** [comment]
So, apparently it *is* ReSharper. I just suspended it in my normal VS 2015 profile and after restarting VS, I can access the Lint properties page and get no errors logged.

**Comment by ReedCopsey** [comment]
@TeaDrivenDev Can you try running with fuslowvw.exe running on the system that's failing, and send a log of the WPF and System.Windows.* errors?

**Comment by dkinitiate** [comment]
Installed latest version of extension from AppVeyor. Upon trying to open lint under options VS crashes, this is what the last exception in activitylog.xml had to say:

```
    Construction of frame content failed.
Frame identifier: ST:0:0:{31fc2115-5126-4a87-b2f7-77eaab65048b}
Frame caption: 
Exception details:
System.ArgumentNullException: 
Parameter name: protocolHandler
   at Microsoft.XamlDiagnostics.UI.LivePropertyExplorer.Model.PropertyExplorerModel..ctor(IProtocolHandler protocolHandler, IActiveElementTracker tracker, ITelemetryLogger telemetryLogger)
   at Microsoft.XamlDiagnostics.Model.XamlDiagnosticsTool.GetPropertyExplorerModel(IServiceProvider serviceProvider)
   at Microsoft.XamlDiagnostics.Model.XamlDiagnosticsTool.CreatePropertyExplorer(IServiceProvider serviceProvider, ResourceDictionary themeDictionary, UIElement searchContentControl)
   at Microsoft.VisualStudio.ClientDiagnostics.XamlDiagnostics.PropertyExplorerToolWindow.GetContent()
   at Microsoft.VisualStudio.ClientDiagnostics.XamlDiagnostics.XamlDiagnosticsToolWindowBase.ShowContent()
   at Microsoft.VisualStudio.ClientDiagnostics.XamlDiagnostics.XamlDiagnosticsToolWindowBase.Initialize()
   at Microsoft.VisualStudio.Shell.WindowPane.InternalSetSite(IServiceProvider p)
   at Microsoft.VisualStudio.Shell.WindowPane.Microsoft.VisualStudio.Shell.Interop.IVsWindowPane.SetSite(IServiceProvider psp)
   at Microsoft.VisualStudio.Shell.WindowPane.Microsoft.VisualStudio.Shell.Interop.IVsUIElementPane.SetUIElementSite(IServiceProvider p)
   at Microsoft.VisualStudio.Platform.WindowManagement.UIElementDocumentObject.SetSite(DocumentObjectSite site)
   at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.InitializeDocumentObject(Object punkView)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.CreateContentPane(FrameMoniker frameMoniker, Boolean isDocument, String lpstrMkDoc, UInt32 eCreateWindowFlags, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid, Guid rguidCmdUI, ViewGroup parent, IVsWindowFrame&amp; ppWindowFrame)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.CreateContentPane(String pszName, Int32 fDockViewOn, Int32 fDocument, String lpstrMkDoc, UInt32 eCreateWindowFlags, UInt32 dwToolWinId, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid, Int32&amp; pfDefaultPosition, Guid&amp; rguidCmdUI, IVsWindowFrame&amp; ppWindowFrame)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, UInt32 flags)
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, ProvideToolWindowAttribute tool)
   at Microsoft.VisualStudio.Shell.Package.FindToolWindow(Type toolWindowType, Int32 id, Boolean create, ProvideToolWindowAttribute tool)
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Guid&amp; toolWindowType, Int32 id)
   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsToolWindowFactory.CreateToolWindow(Guid&amp; toolWindowType, UInt32 id)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()
```

Did not happen in the experimental hive.

**Comment by TeaDrivenDev** [comment]
@ReedCopsey Even when I set it to "Log all binds to disk", `System.Windows` does not show up in the entire log from starting VS until activating the "Lint" properties page.

Another thing that might be worth a try (now that we probably know the culprit) is installing ReSharper in the `Exp` hive and then debugging VFPT.

**Comment by ReedCopsey** [comment]
@duckmatt @dungpa This could be worked around by just removing the references to System.Windows.Interactive here https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools.Logic/LintOptionsPageControl.xaml#L83-L85 and https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools.Logic/LintOptionsPageControl.xaml#L8  and then, instead, hooking into an event like this one https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools.Logic/Linting/LintOptionsPageControl.xaml.fs#L54

All it's doing is firing the command - that could be handled by an event instead.

**Comment by dungpa** [comment]
@TeaDrivenDev @sideeffffect We need help to verify whether the bug has been fixed in https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/2.2.0-a1510140720/artifacts ? 

Thank you.

**Comment by TeaDrivenDev** [comment]
@dungpa Yes, it is for VS 2015; it doesn't even offer installing to 2013, though.

**Comment by sideeffffect** [comment]
works on VS 2013 :smile:
thank you

**Comment by dungpa** [comment]
Thanks guys.

**Comment by TeaDrivenDev** [comment]
Any idea why I might not be able to install this in VS 2013? I can (re)install the released version from the gallery, and I could install yesterday's version with the extended logging, but this VSIX behaves as if it was built for 2015 only.

**Comment by dungpa** [comment]
The two versions in this thread have the same version number, so you have to uninstall it from VS 2013 before installing again. VSIX installers skip VS 2013 because it sees that the same version has been installed.

**Comment by TeaDrivenDev** [comment]
That worked for 2015, but I still get "This extension is already installed to all applicable products." after uninstalling from 2013 and running the VSIX. Oh, and that happens now with yesterday's version too, which I could install then. Installing the released version from the gallery still works fine. It looks like it thinks 2.1.1 is still installed (but lets me install 2.1.0 nonetheless). I have tried all the cleanup methods from yesterday again, but none helped.
