### ISSUE TITLE
Intermittent "Assertion Failed" dialogs when editing file in experimental instance

### ISSUE THREAD

**Issue by TeaDrivenDev** [fsprojects/VisualFSharpPowerTools#1157]
I am "randomly" getting a dialog showing this stack trace while editing a (generally error free) .fsx file in a VS experimental instance - is that an error or just a development check?

---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Attempting to create a SnapshotSpan (StartLine = 77, StartColumn = 4, EndLine = 77, EndColumn = 5) in a snapshot length = 2268 results in: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.

Parameter name: span
   at Microsoft.VisualStudio.Text.SnapshotSpan..ctor(ITextSnapshot snapshot, Span span)
   at Microsoft.VisualStudio.Text.SnapshotSpan..ctor(ITextSnapshot snapshot, Int32 start, Int32 length)
   at FSharpVSPowerTools.ProjectSystem.VSUtils.fromRange(ITextSnapshot snapshot, Int32 startLine, Int32 startColumn, Int32 endLine, Int32 endColumn) in D:\Development\OpenSource\VisualFSharpPowerTools\src\FSharpVSPowerTools.Logic\VSUtils.fs:line 20
   at FSharpVSPowerTools.ProjectSystem.VSUtils.fromRange@22-6.Invoke(String arg00) in D:\Development\OpenSource\VisualFSharpPowerTools\src\FSharpVSPowerTools.Logic\VSUtils.fs:line 22
   at FSharpVSPowerTools.ProjectSystem.VSUtils.fromRange@22-12.Invoke(Exception arg60) in D:\Development\OpenSource\VisualFSharpPowerTools\src\FSharpVSPowerTools.Logic\VSUtils.fs:line 22
   at FSharpVSPowerTools.ProjectSystem.VSUtils.fromRange(ITextSnapshot snapshot, Int32 startLine, Int32 startColumn, Int32 endLine, Int32 endColumn) in D:\Development\OpenSource\VisualFSharpPowerTools\src\FSharpVSPowerTools.Logic\VSUtils.fs:line 22
   at FSharpVSPowerTools.ProjectSystem.VSUtils.fromFSharpRange(ITextSnapshot snapshot, range r) in D:\Development\OpenSource\VisualFSharpPowerTools\src\FSharpVSPowerTools.Logic\VSUtils.fs:line 29
   at <StartupCode$FSharpVSPowerTools-Logic>.$LintTagger.clo@68-333.Invoke(Warning warn) in D:\Development\OpenSource\VisualFSharpPowerTools\src\FSharpVSPowerTools.Logic\LintTagger.fs:line 79
   at Microsoft.FSharp.Collections.IEnumerator.choose@154.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at <StartupCode$FSharpVSPowerTools-Logic>.$LintTagger.clo@41-332.Invoke(ParsedInput _arg5) in D:\Development\OpenSource\VisualFSharpPowerTools\src\FSharpVSPowerTools.Logic\LintTagger.fs:line 67
   at <StartupCode$FSharpVSPowerTools-Core>.$Utils.Bind@357-4.Invoke(Unit unitVar) in D:\Development\OpenSource\VisualFSharpPowerTools\src\FSharpVSPowerTools.Core\Utils.fs:line 359
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@803.Invoke(AsyncParams`1 args)
   at <StartupCode$FSharp-Core>.$Control.loop@425-40(Trampoline this, FSharpFunc`2 action)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction)
   at Microsoft.FSharp.Control.TrampolineHolder.Protect(FSharpFunc`2 firstAction)
   at <StartupCode$FSharp-Core>.$Control.-ctor@510-1.Invoke(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by vasily-kirichenko** [comment]
It's an all-time known issue. It's not appear in release configuration.
