### ISSUE TITLE
[Outlining] Lots of exceptions in the log

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1247]
*Lots* of exception in our log:
```
[VFPT][Error 10:52:26 ] Exception Message: Specified argument was out of the range of valid values.
Parameter name: lineNumber
Stack Trace:    at Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetLineFromLineNumber(Int32 lineNumber)
   at Microsoft.VisualStudio.Text.Implementation.TextSnapshot.GetLineFromLineNumber(Int32 lineNumber)
   at FSharpVSPowerTools.ProjectSystem.VSUtils.fromRange(ITextSnapshot snapshot, Int32 startLine, Int32 startColumn, Int32 endLine, Int32 endColumn) in D:\git\VisualFSharpPowerTools\src\FSharpVSPowerTools.Logic\VSUtils.fs:line 36
[VFPT][Error 10:52:31 ] Exception Message: Specified argument was out of the range of valid values.
Parameter name: lineNumber
Stack Trace:    at Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetLineFromLineNumber(Int32 lineNumber)
   at Microsoft.VisualStudio.Text.Implementation.TextSnapshot.GetLineFromLineNumber(Int32 lineNumber)
   at FSharpVSPowerTools.ProjectSystem.VSUtils.fromRange(ITextSnapshot snapshot, Int32 startLine, Int32 startColumn, Int32 endLine, Int32 endColumn) in D:\git\VisualFSharpPowerTools\src\FSharpVSPowerTools.Logic\VSUtils.fs:line 36
[VFPT][Error 10:52:31 ] Exception Message: Specified argument was out of the range of valid values.
Parameter name: lineNumber
Stack Trace:    at Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetLineFromLineNumber(Int32 lineNumber)
   at Microsoft.VisualStudio.Text.Implementation.TextSnapshot.GetLineFromLineNumber(Int32 lineNumber)
   at FSharpVSPowerTools.ProjectSystem.VSUtils.fromRange(ITextSnapshot snapshot, Int32 startLine, Int32 startColumn, Int32 endLine, Int32 endColumn) in D:\git\VisualFSharpPowerTools\src\FSharpVSPowerTools.Logic\VSUtils.fs:line 36
```
It seems `ScopeSpan`s contain very wrong `EndLine`:

![6677](https://cloud.githubusercontent.com/assets/873919/11162674/1fd75ee8-8abe-11e5-93d3-b659c43334c2.gif)

**Comment by vasily-kirichenko** [comment]
It doesn't influence any feature, so I'm closing it.
