### ISSUE TITLE
[Outlining] ObjectDisposedException in log

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1256]
```
[VFPT][Error 04:06:04 ] Exception Message: Cannot access a disposed object.
Object name: 'OutliningManager'.
Stack Trace:    at Microsoft.VisualStudio.Text.Outlining.OutliningManager.EnsureValid()
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.EnsureValid(SnapshotSpan span)
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.CollapseAll(SnapshotSpan span, Predicate`1 match)
   at FSharpVSPowerTools.OutliningTaggerProvider.<>c__DisplayClass7.<TextViewCreated>b__4(Object sender, SnapshotSpanEventArgs e) in d:\github\FSharpVSPowerTools\src\FSharpVSPowerTools\Commands\OutliningTaggerProvider.cs:line 90
   at Microsoft.FSharp.Control.FSharpEvent`2.Trigger(Object sender, TArgs args)
   at FSharpVSPowerTools.Outlining.OutliningTagger.triggerUpdate(ScopeSpan[] newSnapshotSpans) in D:\github\FSharpVSPowerTools\src\FSharpVSPowerTools.Logic\Outlining\OutliningTagger.fs:line 90
   at FSharpVSPowerTools.Outlining.clo@178-495.Invoke(Unit _arg1) in D:\github\FSharpVSPowerTools\src\FSharpVSPowerTools.Logic\Outlining\OutliningTagger.fs:line 178
   at FSharpVSPowerTools.ProjectSystem.VSUtils.protectOrDefault[a](FSharpFunc`2 f, a defaultVal) in D:\github\FSharpVSPowerTools\src\FSharpVSPowerTools.Logic\VSUtils.fs:line 431
```

**Comment by dungpa** [comment]
Is this with current master? Do you have a reliable way to reproduce this?

**Comment by vasily-kirichenko** [comment]
yes, it's with current master. I happened on just after a file was opened. I'll try to make minimal repro.

**Comment by dungpa** [comment]
Does this still occur? It might not happen any more due to #1260.

**Comment by vasily-kirichenko** [comment]
I have not checked but it's definetely fixed.

**Comment by vasily-kirichenko** [comment]
Master, VS 2015 Update 1:

```
[VFPT][Error 11:24:41 AM] Exception Message: Cannot access a disposed object.
Object name: 'OutliningManager'.
Stack Trace:    at Microsoft.VisualStudio.Text.Outlining.OutliningManager.EnsureValid()
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.EnsureValid(SnapshotSpan span)
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.InternalCollapseAll(SnapshotSpan span, Predicate`1 match, Nullable`1 cancel)
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.CollapseAll(SnapshotSpan span, Predicate`1 match)
   at FSharpVSPowerTools.OutliningTaggerProvider.<>c__DisplayClass10_0.<TextViewCreated>b__0(Object sender, SnapshotSpanEventArgs e)
   at Microsoft.FSharp.Control.FSharpEvent`2.Trigger(Object sender, TArgs args)
   at FSharpVSPowerTools.Outlining.clo@178-459.Invoke(Unit _arg1)
   at FSharpVSPowerTools.ProjectSystem.VSUtils.protectOrDefault[a](FSharpFunc`2 f, a defaultVal)
```

**Comment by dungpa** [comment]
Is this still happening?

**Comment by vasily-kirichenko** [comment]
I think it does not matter even though it's still happening, everything work ok.
