### ISSUE TITLE
[Tasks] Exception

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1276]
```
[VFPT][Error 03:27:41 PM] Exception Message: Expression of type 'Microsoft.FSharp.Core.FSharpOption`1[System.Tuple`2[System.String[],System.String[]]]' cannot be used for return type 'Microsoft.FSharp.Core.FSharpOption`1[System.Tuple`2[System.String[],System.String[]]]'
Stack Trace:    at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, ParameterExpression[] parameters)
   at FSharpVSPowerTools.Reflection.precompileFieldGet[R](FieldInfo f)
   at FSharpVSPowerTools.ProjectSystem.ProjectProvider..ctor(Project project, FSharpFunc`2 getProjectProvider, FSharpFunc`2 onChanged)
   at <StartupCode$FSharpVSPowerTools-Logic>.$ProjectFactory.CreateForProject@119.Invoke(Unit _arg8)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at FSharpVSPowerTools.ProjectSystem.Cache`2.Get(K key, FSharpFunc`2 creator)
   at FSharpVSPowerTools.ProjectSystem.ProjectFactory.CreateForProject(Project project)
   at Microsoft.FSharp.Collections.IEnumerator.map@109.DoMoveNext(b& )
   at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.IEnumerator.map@109.DoMoveNext(b& )
   at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeOuter@667[T,TResult](ConcatEnumerator`2 x, Unit unitVar0)
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at <StartupCode$FSharpVSPowerTools-Logic>.$CrossSolutionTaskListCommentManager.clo@101-395.Invoke(Unit _arg3)
   at FSharpVSPowerTools.ProjectSystem.VSUtils.time[a](String label, FSharpFunc`2 f)
   at <StartupCode$FSharpVSPowerTools-Logic>.$CrossSolutionTaskListCommentManager.clo@101-394.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@769.Invoke(AsyncParams`1 args)
```

**Comment by vasily-kirichenko** [comment]
It's everywhere:
```
[VFPT][Error 03:32:36 PM] Exception Message: Expression of type 'Microsoft.FSharp.Core.FSharpOption`1[System.Tuple`2[System.String[],System.String[]]]' cannot be used for return type 'Microsoft.FSharp.Core.FSharpOption`1[System.Tuple`2[System.String[],System.String[]]]'
Stack Trace:    at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, ParameterExpression[] parameters)
   at FSharpVSPowerTools.Reflection.precompileFieldGet[R](FieldInfo f)
   at FSharpVSPowerTools.ProjectSystem.ProjectProvider..ctor(Project project, FSharpFunc`2 getProjectProvider, FSharpFunc`2 onChanged)
   at <StartupCode$FSharpVSPowerTools-Logic>.$ProjectFactory.CreateForProject@119.Invoke(Unit _arg8)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at FSharpVSPowerTools.ProjectSystem.Cache`2.Get(K key, FSharpFunc`2 creator)
   at FSharpVSPowerTools.ProjectSystem.ProjectFactory.CreateForProject(Project project)
   at FSharpVSPowerTools.ProjectSystem.ProjectFactory.CreateForDocument(ITextBuffer buffer, Document doc)
   at <StartupCode$FSharpVSPowerTools-Logic>.$UnionPatternMatchCaseGeneratorSmartTagger.clo@69-353.Invoke(Document _arg3)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@769.Invoke(AsyncParams`1 args)
```

**Comment by vasily-kirichenko** [comment]
Maybe it's because VFT uses FSharp.Core 4.4.0.0?

**Comment by dungpa** [comment]
Look like it is. But why it happens now and not in VS 2015 RTM.

**Comment by vasily-kirichenko** [comment]
I didn't test Tasks in VS 2015 RTM. 

I turned off the feature and no errors in Update 1.

**Comment by vasily-kirichenko** [comment]
I'm closing it because I cannot reproduce it in VS 2015 Update 1.
