### ISSUE TITLE
[Coloring] Stops working for no reason

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#1299]
Current master. At some point, with no clear reason, coloring stops working - already colorized spans are still colorized, but new ones - are not. No usual logging in the Output window ([Fast stage] ..., [Slow stage] ...)

**Comment by dungpa** [comment]
Are in the new spans at the end or in the middle of the file? It looks like the logic to avoid reparse is still flawed.

**Comment by vasily-kirichenko** [comment]
It's not the case. I guess it stops receiving callbacks from `DocumentEnentListener`. I could not reproduce it yesterday, will keep an eye on it today.

**Comment by vasily-kirichenko** [comment]
It happend again. It seems it's caused by the old good `OutlineManager`'s "Cannot access a disposed object" exception:
```
[VFPT][Information 03:16:19 PM] [SyntaxConstructClassifier] Replace spans entirely because new spans has no errors.
[VFPT][Information 03:16:19 PM] [SyntaxConstructClassifier] [Normal stage] 00:00:00.0563588 elapsed
[VFPT][Information 03:16:19 PM] [SyntaxConstructClassifier] [Normal stage] 00:00:00.0476549 elapsed
[VFPT][Information 03:16:19 PM] [SyntaxConstructClassifier] Replace spans entirely because new spans has no errors.
[VFPT][Information 03:16:19 PM] [SyntaxConstructClassifier] Replace spans entirely because new spans has no errors.
[VFPT][Information 03:16:19 PM] [SyntaxConstructClassifier] [Normal stage] 00:00:00.0563103 elapsed
[VFPT][Information 03:16:19 PM] [SyntaxConstructClassifier] [Normal stage] 00:00:00.0624058 elapsed
[VFPT][Error 03:18:10 PM] Exception Message: Cannot access a disposed object.
Object name: 'OutliningManager'.
Stack Trace:    at Microsoft.VisualStudio.Text.Outlining.OutliningManager.EnsureValid()
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.EnsureValid(SnapshotSpan span)
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.InternalCollapseAll(SnapshotSpan span, Predicate`1 match, Nullable`1 cancel)
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.CollapseAll(SnapshotSpan span, Predicate`1 match)
   at FSharpVSPowerTools.Outlining.OutliningTaggerProvider.<>c__DisplayClass10_0.<TextViewCreated>b__0(Object sender, SnapshotSpanEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Microsoft.FSharp.Control.FSharpEvent`2.Trigger(Object sender, TArgs args)
   at FSharpVSPowerTools.Outlining.OutliningTagger.triggerUpdate(ScopeSpan[] newSnapshotSpans)
   at <StartupCode$FSharpVSPowerTools-Logic>.$OutliningTagger.clo@179-513.Invoke(Unit _arg1)
   at FSharpVSPowerTools.ProjectSystem.VSUtils.protectOrDefault[a](FSharpFunc`2 f, a defaultVal)
[VFPT][Error 03:18:10 PM] Exception Message: Cannot access a disposed object.
Object name: 'OutliningManager'.
Stack Trace:    at Microsoft.VisualStudio.Text.Outlining.OutliningManager.EnsureValid()
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.EnsureValid(SnapshotSpan span)
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.InternalCollapseAll(SnapshotSpan span, Predicate`1 match, Nullable`1 cancel)
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.CollapseAll(SnapshotSpan span, Predicate`1 match)
   at FSharpVSPowerTools.Outlining.OutliningTaggerProvider.<>c__DisplayClass10_0.<TextViewCreated>b__0(Object sender, SnapshotSpanEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Microsoft.FSharp.Control.FSharpEvent`2.Trigger(Object sender, TArgs args)
   at FSharpVSPowerTools.Outlining.OutliningTagger.triggerUpdate(ScopeSpan[] newSnapshotSpans)
   at <StartupCode$FSharpVSPowerTools-Logic>.$OutliningTagger.clo@179-513.Invoke(Unit _arg1)
   at FSharpVSPowerTools.ProjectSystem.VSUtils.protectOrDefault[a](FSharpFunc`2 f, a defaultVal)
[VFPT][Error 03:18:12 PM] Exception Message: Cannot access a disposed object.
Object name: 'OutliningManager'.
Stack Trace:    at Microsoft.VisualStudio.Text.Outlining.OutliningManager.EnsureValid()
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.EnsureValid(SnapshotSpan span)
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.InternalCollapseAll(SnapshotSpan span, Predicate`1 match, Nullable`1 cancel)
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.CollapseAll(SnapshotSpan span, Predicate`1 match)
   at FSharpVSPowerTools.Outlining.OutliningTaggerProvider.<>c__DisplayClass10_0.<TextViewCreated>b__0(Object sender, SnapshotSpanEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Microsoft.FSharp.Control.FSharpEvent`2.Trigger(Object sender, TArgs args)
   at FSharpVSPowerTools.Outlining.OutliningTagger.triggerUpdate(ScopeSpan[] newSnapshotSpans)
   at <StartupCode$FSharpVSPowerTools-Logic>.$OutliningTagger.clo@179-513.Invoke(Unit _arg1)
   at FSharpVSPowerTools.ProjectSystem.VSUtils.protectOrDefault[a](FSharpFunc`2 f, a defaultVal)
[VFPT][Error 03:18:12 PM] Exception Message: Cannot access a disposed object.
Object name: 'OutliningManager'.
Stack Trace:    at Microsoft.VisualStudio.Text.Outlining.OutliningManager.EnsureValid()
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.EnsureValid(SnapshotSpan span)
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.InternalCollapseAll(SnapshotSpan span, Predicate`1 match, Nullable`1 cancel)
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.CollapseAll(SnapshotSpan span, Predicate`1 match)
   at FSharpVSPowerTools.Outlining.OutliningTaggerProvider.<>c__DisplayClass10_0.<TextViewCreated>b__0(Object sender, SnapshotSpanEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Microsoft.FSharp.Control.FSharpEvent`2.Trigger(Object sender, TArgs args)
   at FSharpVSPowerTools.Outlining.OutliningTagger.triggerUpdate(ScopeSpan[] newSnapshotSpans)
   at <StartupCode$FSharpVSPowerTools-Logic>.$OutliningTagger.clo@179-513.Invoke(Unit _arg1)
   at FSharpVSPowerTools.ProjectSystem.VSUtils.protectOrDefault[a](FSharpFunc`2 f, a defaultVal)
[VFPT][Error 03:18:13 PM] Exception Message: Cannot access a disposed object.
Object name: 'OutliningManager'.
Stack Trace:    at Microsoft.VisualStudio.Text.Outlining.OutliningManager.EnsureValid()
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.EnsureValid(SnapshotSpan span)
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.InternalCollapseAll(SnapshotSpan span, Predicate`1 match, Nullable`1 cancel)
   at Microsoft.VisualStudio.Text.Outlining.OutliningManager.CollapseAll(SnapshotSpan span, Predicate`1 match)
   at FSharpVSPowerTools.Outlining.OutliningTaggerProvider.<>c__DisplayClass10_0.<TextViewCreated>b__0(Object sender, SnapshotSpanEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Microsoft.FSharp.Control.FSharpEvent`2.Trigger(Object sender, TArgs args)
   at FSharpVSPowerTools.Outlining.OutliningTagger.triggerUpdate(ScopeSpan[] newSnapshotSpans)
   at <StartupCode$FSharpVSPowerTools-Logic>.$OutliningTagger.clo@179-513.Invoke(Unit _arg1)
   at FSharpVSPowerTools.ProjectSystem.VSUtils.protectOrDefault[a](FSharpFunc`2 f, a defaultVal)
```
After first exception there are no "SyntaxConstructClassifier" in the log.

**Comment by vasily-kirichenko** [comment]
![image](https://cloud.githubusercontent.com/assets/873919/11897098/a1214dde-a59d-11e5-9411-71f57034870f.png)

![image](https://cloud.githubusercontent.com/assets/873919/11897110/bd3dd01e-a59d-11e5-8399-c97bc07fdd2b.png)

**Comment by dungpa** [comment]
How do you reproduce this (on VS2015 of course)? Do you have a stacktrace where the object is disposed.
