### ISSUE TITLE
Extension doesn't install with .NET Framework 4.6

### ISSUE THREAD

**Issue by ane** [fsprojects/VisualFSharpPowerTools#929]
I installed Visual Studio 2015 CTP 5 which installs .NET Framework 4.6 with it automatically.

The .vsix extension refuses to install because it doesn't recognize this target framework.

Here is the install log: 

```
5.2.2015 14:43:53 - Microsoft VSIX Installer
5.2.2015 14:43:53 - -------------------------------------------
5.2.2015 14:43:53 - Initializing Install...
5.2.2015 14:43:53 - Extension Details...
5.2.2015 14:43:53 - 	Identifier      : FSharpVSPowerTools.68b42cfe-c752-4094-8dba-ed48aa81cac8
5.2.2015 14:43:53 - 	Name            : Visual F# Power Tools
5.2.2015 14:43:53 - 	Author          : fsharp.org
5.2.2015 14:43:53 - 	Version         : 1.7.0
5.2.2015 14:43:53 - 	Description     : A collection of additional commands for F# in Visual Studio
5.2.2015 14:43:53 - 	Locale          : en-US
5.2.2015 14:43:53 - 	MoreInfoURL     : https://github.com/fsprojects/VisualFSharpPowerTools
5.2.2015 14:43:53 - 	InstalledByMSI  : False
5.2.2015 14:43:53 - 	SupportedFrameworkVersionRange : [4.5]
5.2.2015 14:43:53 - 
5.2.2015 14:43:53 - 	Supported Products : 
5.2.2015 14:43:53 - 		Microsoft.VisualStudio.Pro
5.2.2015 14:43:53 - 			Version : [11.0]
5.2.2015 14:43:53 - 		Microsoft.VisualStudio.Pro
5.2.2015 14:43:53 - 			Version : [12.0,13.0)
5.2.2015 14:43:53 - 		Microsoft.VisualStudio.Pro
5.2.2015 14:43:53 - 			Version : [13.0,15.0)
5.2.2015 14:43:53 - 
5.2.2015 14:43:53 - 	References      : 
5.2.2015 14:43:53 - 		-------------------------------------------------------
5.2.2015 14:43:53 - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
5.2.2015 14:43:53 - 		Name         : Visual Studio MPF 11.0
5.2.2015 14:43:53 - 		Version      : [11.0]
5.2.2015 14:43:53 - 		MoreInfoURL  : 
5.2.2015 14:43:53 - 		Nested       : No
5.2.2015 14:43:53 - 
5.2.2015 14:43:53 - 
5.2.2015 14:43:53 - Searching for applicable products...
5.2.2015 14:43:54 - Found installed product - Microsoft Visual Studio Express 2012 for Web
5.2.2015 14:43:54 - Found installed product - Microsoft Visual Studio Premium 2013 
5.2.2015 14:43:56 - The extension will be upgraded from version 1.6.1.
5.2.2015 14:43:56 - Found installed product - Microsoft Visual Studio Professional 2013
5.2.2015 14:43:56 - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
5.2.2015 14:43:56 - Found installed product - Microsoft Visual Studio Ultimate 2015 CTP
5.2.2015 14:43:59 - The extension with ID 'FSharpVSPowerTools.68b42cfe-c752-4094-8dba-ed48aa81cac8' is not installed to Microsoft Visual Studio Ultimate 2015 CTP.
5.2.2015 14:43:59 - Found installed product - Microsoft Visual Studio Premium 2015 CTP
5.2.2015 14:43:59 - Found installed product - Microsoft Visual Studio Professional 2015 CTP
5.2.2015 14:43:59 - Found installed product - Microsoft Visual Studio Community 2015 CTP
5.2.2015 14:43:59 - Found installed product - Microsoft Visual Studio 2015 CTP Shell (Integrated)
5.2.2015 14:43:59 - Found installed product - Global Location
5.2.2015 14:44:02 - The following target products have been selected...
5.2.2015 14:44:02 - 	Microsoft Visual Studio Ultimate 2015 CTP
5.2.2015 14:44:02 - 
5.2.2015 14:44:02 - Beginning to install extension to Microsoft Visual Studio Ultimate 2015 CTP...
5.2.2015 14:44:02 - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingTargetFrameworkException: The extension 'Visual F# Power Tools' requires a version of the .NET Framework that is not installed.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForValidDotNetFramework(IExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp)

```

**Comment by dungpa** [comment]
It's the same problem as #923. This has been fixed in v1.7.2 https://ci.appveyor.com/project/dungpa/visualfsharppowertools/build/1.8.0-a1501172312/artifacts.

Perhaps I should update the version in VS Gallery to the new one.

**Comment by dungpa** [comment]
Ok, the new version (v1.7.2) is available on VS Gallery. Please give it a try.

**Comment by ane** [comment]
It works indeed. Thank you! Should've searched in closed issues.

**Comment by yukitos** [comment]
@dungpa Thank you for releasing v1.7.2 early.
BTW, it seems that '1.7.2' is not yet tagged in this repository, so is this still tentative one?

**Comment by dungpa** [comment]
@yukitos Thanks for the reminder. I pushed the release to GitHub.

**Comment by yukitos** [comment]
:+1:
