### ISSUE TITLE
[Coloring] Exception in `FSharpVSPowerTools.StringCategorizers.EscapedChars.isRegularString`

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#978]
```
[VFPT][Error 11:20:43 ] Exception Message: startIndex cannot be larger than length of string.
Parameter name: startIndex
Stack Trace:    at System.String.Substring(Int32 startIndex, Int32 length)
   at FSharpVSPowerTools.StringCategorizers.EscapedChars.isRegularString(range r, FSharpFunc`2 getTextLine)
   at FSharpVSPowerTools.StringCategorizers.EscapedChars.getCategories@131-1.Invoke(range r)
   at Microsoft.FSharp.Primitives.Basics.List.filter[T](FSharpFunc`2 predicate, FSharpList`1 l)
   at FSharpVSPowerTools.StringCategorizers.EscapedChars.getCategories[a](FSharpOption`1 ast, FSharpFunc`2 getTextLine)
   at FSharpVSPowerTools.SourceCodeClassifier.getCategoriesAndLocations[a](SymbolUse[] allSymbolsUses, ParseAndCheckResults checkResults, LexerBase lexer, FSharpFunc`2 getTextLine, FSharpList`1 openDeclarations, FSharpOption`1 allEntities)
   at <StartupCode$FSharpVSPowerTools-Logic>.$SyntaxConstructClassifier.spans@262-2.Invoke(Unit _arg12)
   at FSharpVSPowerTools.Profiler.Time[b](String msg, FSharpFunc`2 f)
   at <StartupCode$FSharpVSPowerTools-Logic>.$SyntaxConstructClassifier.worker@260-31.Invoke(SymbolUse[] _arg11)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@787-1.Invoke(a a)
```

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/fsprojects/VisualFSharpPowerTools/pull/975
