### ISSUE TITLE
[Coloring] Exception in `FSharpVSPowerTools.StringCategorizers.lines`

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/VisualFSharpPowerTools#979]
```
[VFPT][Error 11:55:59 ] Exception Message: startIndex cannot be larger than length of string.
Parameter name: startIndex
Stack Trace:    at System.String.Substring(Int32 startIndex, Int32 length)
   at FSharpVSPowerTools.StringCategorizers.lines@89.Invoke(Int32 line)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
   at FSharpVSPowerTools.StringCategorizers.categorize[a](Category category, Regex regex, FSharpFunc`2 getTextLine, range r)
   at FSharpVSPowerTools.StringCategorizers.EscapedChars.getCategories@134.Invoke(range r)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
   at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list)
   at FSharpVSPowerTools.StringCategorizers.EscapedChars.getCategories[a](FSharpOption`1 ast, FSharpFunc`2 getTextLine)
   at FSharpVSPowerTools.SourceCodeClassifier.getCategoriesAndLocations[a](SymbolUse[] allSymbolsUses, ParseAndCheckResults checkResults, LexerBase lexer, FSharpFunc`2 getTextLine, FSharpList`1 openDeclarations, FSharpOption`1 allEntities)
   at <StartupCode$FSharpVSPowerTools-Logic>.$SyntaxConstructClassifier.spans@262-2.Invoke(Unit _arg12)
   at FSharpVSPowerTools.Profiler.Time[b](String msg, FSharpFunc`2 f)
   at <StartupCode$FSharpVSPowerTools-Logic>.$SyntaxConstructClassifier.worker@260-31.Invoke(SymbolUse[] _arg11)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@787-1.Invoke(a a)
```

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/fsprojects/VisualFSharpPowerTools/pull/975
